#Deprecated. Prefer to use the one in corobot_srvs package, which is exactly the same

#
# Morgan Cormier <mcormier@coroware.com>
#
# Service used to know the maximum number of motors connectable to the Phidget device.
#
# numberMotors is the maximum number of motors that can be connected to the Phidget device

---
int8 numberMotors
